Fix shifting automap markers
coelckers/prboom-plus pull request #260
Opened 2021-03-30 06:48 UTC by TwelveEyes

The drawn patch for the automap marker number always assumed `patch_stretch_full` as the stretch setting, so on `patch_stretch_16x10` or `patch_stretch_4x3` the marker position was not being set correctly. This should correct the behavior for opengl & software, all resolutions, aspect ratios, and stretch settings. Unfortunately I was unable to test every possibility, so there may still be unintended behavior.

Fixes #90

2021-03-30 07:40 UTC, fabiangreffrath requested changes
Cool, thanks! It's just a matter of style, but since only the x and y coordinates and the flags change between the three possible `render_stretch_hud` values, you could only adjust these in the `switch` block and then call the patch drawing function based `am_frame.precise` - just as it was before. This will make the code a bit easier to read and highlight the actual differences in the arguments.

2021-03-30 13:36 UTC, TwelveEyes commented
Did you mean like this?

```diff
--- a/prboom2/src/am_map.c
+++ b/prboom2/src/am_map.c
@@ -2137,17 +2137,47 @@ static void AM_drawMarks(void)
           if (p.x < f_x + f_w &&
               p.x + markpoints[i].widths[k] * SCREENWIDTH / 320 >= f_x)
           {
+            float fx, fy;
+            int x, y, flags;
+
+            switch (render_stretch_hud)
+            {
+              case patch_stretch_16x10:
+                fx = (float)p.fx / patches_scalex;
+                fy = (float)p.fy * 200.0f / SCREENHEIGHT;
+
+                x = p.x / patches_scalex;
+                y = p.y * 200 / SCREENHEIGHT;
+
+                flags = VPT_ALIGN_LEFT | VPT_STRETCH;
+                break;
+              case patch_stretch_4x3:
+                fx = (float)p.fx * 320.0f / WIDE_SCREENWIDTH;
+                fy = (float)p.fy * 200.0f / WIDE_SCREENHEIGHT;
+
+                x = p.x * 320 / WIDE_SCREENWIDTH;
+                y = p.y * 200 / WIDE_SCREENHEIGHT;
+                
+                flags = VPT_ALIGN_LEFT | VPT_STRETCH;
+                break;
+              case patch_stretch_full:
+                fx = (float)p.fx * 320.0f / SCREENWIDTH;
+                fy = (float)p.fy * 200.0f / SCREENHEIGHT;
+
+                x = p.x * 320 / SCREENWIDTH;
+                y = p.y * 200 / SCREENHEIGHT;
+                
+                flags = VPT_ALIGN_WIDE | VPT_STRETCH;
+                break;
+            }
+
             if (am_frame.precise)
             {
-              V_DrawNamePatchPrecise(
-                (float)p.fx * 320.0f / SCREENWIDTH, (float)p.fy * 200.0f / SCREENHEIGHT,
-                FB, namebuf, CR_DEFAULT, VPT_ALIGN_WIDE | VPT_STRETCH);
+              V_DrawNamePatchPrecise(fx, fy, FB, namebuf, CR_DEFAULT, flags);
             else
             {
-              V_DrawNamePatch(
-                p.x * 320 / SCREENWIDTH, p.y * 200 / SCREENHEIGHT,
-                FB, namebuf, CR_DEFAULT, VPT_ALIGN_WIDE | VPT_STRETCH);
+              V_DrawNamePatch(x, y, FB, namebuf, CR_DEFAULT, flags);
             }
           }
```

2021-03-30 14:03 UTC, fabiangreffrath commented
Beautiful.

2021-03-30 14:30 UTC, TwelveEyes commented
Alright, requested changes have been made.

2021-03-31 18:57 UTC, fabiangreffrath approved these changes
I had no chance to check if this fixes the issue for all possible values of `render_stretch_hud`, but code wise it looks fine.

2021-03-31 22:05 UTC, fabiangreffrath commented
All seems fine, thanks!

2021-03-31 22:05 UTC, merged